# Information
site_name: 'SeAT Documentation'
site_description: 'Simple EVE Api Tool Documentation'
site_url: 'https://github.com/eveseat/docs'

# Repository
repo_name: 'eveseat/docs'
repo_url: 'https://github.com/eveseat/docs'

# Copyright
copyright: 'Copyright &copy; 2015 - 2018 Leon Jacobs'

# Documentation TOC
pages:
    - Home: index.md

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/eveseat/seat'
